image: php:7.3.15

pipelines:
  default:
    - step:
        caches:
          - composer
        script:
          - apt-get update && apt-get install -y unzip
          - curl -sS https://getcomposer.org/installer | php && mv composer.phar /usr/local/bin/composer
          - composer global require hirak/prestissimo  --no-plugins --no-scripts
          - composer install --no-progress --no-suggest
          - composer test
